// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	Email     string    `json:"email"`
	Followers []*string `json:"followers"`
	Following []*string `json:"following"`
	Password  string    `json:"password"`
}

type UserInput struct {
	Email     string    `json:"email"`
	Followers []*string `json:"followers"`
	Following []*string `json:"following"`
	Password  string    `json:"password"`
}

type UserOutput struct {
	Email     string    `json:"email"`
	Followers []*string `json:"followers"`
	Following []*string `json:"following"`
}
